#!/bin/sh
# script config infondlinux
# distributed under New BSD Licence
# created by t0ka7a
# version 0.2
# this script makes a post-installation on Ubuntu
# careful: the script stops firefox if it is running.

# debian packages
# - vim 
# - less 
# - gimp 
# - wipe 
# - xchat 
# - pidgin 
# - tor 
# - vlc 
# - nautilus-open-terminal
# - nmap
# - openjdk-6-jre
# - bluefish
# - flash-plugin-nonfree
# - aircrack-ng
# - wireshark
# - ruby
# - ascii

# manually downloaded softwares and version
# - dirBuster-1.0-RC1 2009-02-27
# - truecrypt-7.0-linux-x86
# - metasploit framework 3.4.1-linux-i386

# firefox extensions
# - livehttpheaders 
# - firebug 
# - tamperdata 
# - noscript 
# - flashblock 
# - flashgot 
# - foxyproxy

#####################################
# function log()
#####################################
# write in /usr/share/infond/log/install.log
# @param1: type '+' or 'E' or 'I'
# @param2: 'message' 
log() (
  echo $1": $(date +%D' '%R':'%S) "$2 >> /usr/share/infond/log/install.log
  echo $1": $(date +%D' '%R':'%S) "$2 > /dev/stdout
)

###########################
# function addBinEntry()
###########################
# adds a file .sh with the command line in the application directory
# adds a symbolic link in /usr/bin
# param1: name of the application
# param2: path to application
# param3: command line (from the application directory)
# param4: term (default=NULL). To start the application in a new term 
# ex: addBinEntry dirbuster "/usr/share/infond/bin/DirBuster-1.0-RC1" "java -jar /usr/share/infond/bin/DirBuster-1.0-RC1/DirBuster-1.0-RC1.jar" term
#     creates a file dirbuster.sh in /usr/share/infond/bin
addBinEntry() (
  # exit if file already in /usr/bin
  [ -z $(ls /usr/bin | grep $1.sh ) ] && log "I" "$1 already in /usr/bin. Not added." && return 1
  
  echo "#!/bin/sh" > /usr/share/infond/bin/$1.sh
  echo "\n\
# $1.sh\n\
# generated by infond post installation infond\n\
# launcher to start $1 in a terminal\n\
# a symbolic link was created in /usr/bin\n" >> /usr/share/infond/bin/$1.sh
  log "+" "$1.sh created in /usr/share/infond/bin/."

  # run application from terminal if $4 set to 'term'
  if ( [ ! -z $4 ] && [ $4 = 'term' ] ); then 
    echo "gnome-terminal --title=$1 --working-directory=$2 --command=\"$3\"" >> /usr/share/infond/bin/$1.sh
  else
    echo "cd $2\n$3" >> /usr/share/infond/bin/$1.sh
  fi

  # make $1.sh executable
  chmod +x /usr/share/infond/bin/$1.sh 
  log "+" "$1.sh chmod +x"

  # remove old link if necessary  
  rm /usr/bin/$1

  # create symbolic link in /usr/bin
  ln -s /usr/share/infond/bin/$1.sh /usr/bin/$1
  log "+" "symbolic link to $1.sh created in /usr/bin/."
)

#####################################
# function aptremove()
#####################################
# remove package using apt
aptremove() ( 
  # if package not installed
  [ -z $(dpkg --list $1 | grep ii) ] && log "I" "$1 not installed. can't be removed" && return 1
  # remove package
  apt-get --auto-remove -y --allow-unauthenticated remove $1
  # if package well removed
  [ -z $(dpkg --list $1 | grep ii) ] && log "+" "$1 removed"   
)

#####################################
# function aptinstall()
#####################################
# install package using apt
aptinstall() (
  # if package already installed 
  [ ! -z "$(dpkg --list $1 | grep ii)" ] && log "I" "$1 already installed. can't be installed" && return 1
  # install package
  apt-get --auto-remove -y --allow-unauthenticated install $1 
  # if package well installed
  [ ! -z "$(dpkg --list $1 | grep ii)" ] && log "+" "$1 installed"
)

#################################
# function firefoxadd()
#################################
# download firefox extension .xpi into /usr/lib/firefox-addons/extensions
# firefox will install it at next sudo start
# @param1: name of the extension
# @param2: number of extension on addons.mozilla.org 
firefoxadd() (
  if [ -z "$(ls -R /usr/lib/firefox-addons/extensions | grep $1)" ]; then 
    wget https://addons.mozilla.org/fr/firefox/downloads/latest/$2/addon-$2-latest.xpi -nc -P /usr/lib/firefox-addons/extensions
    log "+" "$1 ready to install."
  else
   log "I" "$1 already installed. .xpi not downloaded."
  fi
)

###########################
# function downloadicon()
###########################
# download picture and create icon
# @param1: name for the icon
# @param2: downloading address
# ex: downloadicon msf http://metasploit.com/icon.jpg
downloadicon() (
  if [ -z "$(ls /usr/share/infond/pictures | grep $1.png )" ]; then
    wget $2 -P /tmp
    convert -size 48x48 /tmp/$(echo $2|awk -F/ '{print $NF}') -resize 48x48 -extent 48x48 +profile '*' /usr/share/infond/pictures/$1.png
    log "+" "$1 icon downloaded"
    rm /tmp/$(echo $2|awk -F/ '{print $NF}')
  else
    log "I" "$1 icon already exists. Not downloaded."
  fi
)

###########################
# function addmenu()
###########################
# add an entry to gnome menu
# @param1: name
# @param2: comment
# @param3: command line
# @param4: terminal (true or false)
# @param5: categorie
addmenu() (
  if [ -z "$(ls /usr/share/applications | grep $1.desktop)" ];then
    echo "
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=$1
Comment=$2
Icon=/usr/share/infond/pictures/$1.png
Exec=$3
Terminal=$4
Categories=$5
" > /usr/share/applications/$1.desktop
    log "+" "$1.desktop created"
  else
    log "I" "$1.desktop already exists. Not updated."
  fi
)


###########################
# function addcategory()
###########################
# add a category to .desktop file
# @param1: name
# @param2: category
addcategory() (
[ -z $(cat /usr/share/applications/$1.desktop | grep $2) ] && sed -i "/Categories/s|$|$2;|" /usr/share/applications/$1.desktop
)

#####################################
# installation start
#####################################
# test sudo
[ $(id -u) -ne "0" ] && echo "You must be sudo to use this script." && exit 1

# mode verbose
#set -v
1>/dev/null
2>/dev/null

# catch CTRL-C
trap "echo ''; echo CTR-C was pressed. Exit; log 'E' 'CTRL-C pressed.; exit 1" 2

# create log file if not already created
echo "****************" >> /usr/share/infond/log/install.log
log "+" "install begin"
echo "****************" >> /usr/share/infond/log/install.log

# create install directory
if [ -z "$(ls /usr/share | grep infond)" ]; then
  mkdir /usr/share/infond
  mkdir /usr/share/infond/bin
  mkdir /usr/share/infond/pictures
  mkdir /usr/share/infond/log
  log "+" "/usr/share/infond and subdirectories created"
else
  log "I" "directory /usr/share/infond already exists. Not updated."
fi

##############################
# 1st start
###############################

# if dist-upgrade not done yet
if [ -z "$(cat /usr/share/infond/log/install.log | grep dist-upgrade )" ]; then

  # dist-upgrade
  apt-get --auto-remove -y --allow-unauthenticated dist-upgrade

  # update log
  log "+" "dist-upgrade"

  # reboot
  echo "System will reboot. Please restart script after reboot"
  read pause 

  # reboot
  log "I" "reboot"
  reboot
fi

#################################
# apt
#################################

# tor
if [ -z "$(cat /etc/apt/sources.list | grep torproject)" ]; then
  echo "" >> /etc/apt/sources.list
  echo "## tor" >> /etc/apt/sources.list
  echo "deb http://deb.torproject.org/torproject.org lucid main" >> /etc/apt/sources.list
  gpg --keyserver keys.gnupg.net --recv 886DDD89
  gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -
  log "+" "tor added to apt sources list"
else
  log "I" "tor already in apt sources list. Not added"
fi

# update
apt-get update > /dev/null
log "+" "apt-get update"

# apt remove useless packages
aptremove gwibber
aptremove empathy
aptremove gbrainy
aptremove f-spot
aptremove evolution
aptremove quadrapassel
aptremove totem

# apt install
aptinstall vim
aptinstall less
aptinstall gimp
aptinstall tor
aptinstall vlc
aptinstall nautilus-open-terminal
aptinstall openjdk-6-jre 
aptinstall flashplugin-nonfree
aptinstall bluefish
aptinstall xchat
aptinstall pidgin
aptinstall ruby

# add category to .desktop
addcategory bluefish Accessories
addcategory xchat Accessories
addcategory pidgin Accessories

##################################
# menu GNOME
##################################

# see $ gnome-help , (search for keyword ".desktop")

# add pictures (if not already in directory)
downloadicon infond http://3.bp.blogspot.com/_Jna6k5HsSu4/TDH4lKIz1cI/AAAAAAAAAHc/a-P6uy2wHjI/s1600/infond48x48.jpg
downloadicon pentest http://3.bp.blogspot.com/_Jna6k5HsSu4/TDMceNplaqI/AAAAAAAAAHs/iWG1MOPS0uw/s320/pentest.png

# add directory entries in /usr/share/infond/desktop-directories
if [ -z "$(ls /usr/share/desktop-directories | grep Infond.directory)" ]; then
  echo "[Desktop Entry]
Name=Infond
Comment=Security tools
Icon=/usr/share/infond/pictures/infond.png
Type=Directory
Categories=Pentest
" > /usr/share/desktop-directories/Infond.directory
  log "+" "Infond.directory written"
else
  log "I" "Infond.directory already exists. Not updated."
fi

if [ -z "$(ls /usr/share/desktop-directories | grep Pentest.directory)" ]; then
  echo "[Desktop Entry]
Name=Pentest
Icon=/usr/share/infond/pictures/pentest.png
Comment=Network pentest oriented applications
Type=Directory
" > /usr/share/desktop-directories/Pentest.directory
  log "+" "Pentest.directory written"
else
  log "I" "Pentest.directory already exists. Not updated."
fi

# modify /etc/xdg/menus/applications.menu
# the directory /etc/xdg is in $XDG_CONFIG_DIRS (see $ gnome-help)
if [ -z "$( cat /etc/xdg/menus/applications.menu | grep Infond.directory )" ]; then
  sed -i '/<!-- Accessories submenu -->/i\
  \
  <!-- Infond submenu -->\
  <Menu>\
    <Name>Infond</Name>\
    <Directory>Infond.directory</Directory>\
    <Menu>\
      <Name>Pentest</Name>\
      <Directory>Pentest.directory</Directory>\
      <Include>\
        <And>\
          <Category>Pentest</Category>\
        </And>\
      </Include>\
    </Menu>\
    <Menu>
      <Name>Accessories</Name>
      <Directory>Utility.directory</Directory>
      <Include>
        <And><Category>Accessories</Category></And>
      </Include>
    </Menu>
  </Menu>\
  ' /etc/xdg/menus/applications.menu
  log "+" "applications.menu modified"
else
  log "I" "applications.menu already correct. Not modified."
fi

##################################
# nmap
##################################

# apt install
aptinstall nmap

# download icon
downloadicon nmap http://www.ansi.tn/gfx/nmap.png

# add entry in Gnome menu
addmenu nmap "Nmap (\"Network Mapper\") is a free and open source utility for network exploration or security auditing." "bash -c 'cd /tmp;nmap -h;nmap -V;bash'" "true" "Pentest"


##################################
# dirBuster-1.0-RC1 2009-02-27
##################################

# install
if [ -z "$(ls /usr/share/infond/bin | grep DirBuster)" ]; then
  wget "http://sourceforge.net/projects/dirbuster/files/DirBuster%20%28jar%20%2B%20lists%29/1.0-RC1/DirBuster-1.0-RC1.tar.bz2/download" -nc -P /tmp
  tar xjvf /tmp/DirBuster* -C /usr/share/infond/bin
  rm /tmp/DirBuster-1.0-RC1.tar.bz2
  log "+" "dirbuster downloaded"
else
  log "I" "dirbuster already in /usr/share/infond/bin. Not downloaded."
fi

# download icon
downloadicon dirbuster http://a.fsdn.com/con/icons/di/dirbuster@sf.net/ologo.gif 

# create dirbuster.sh and add dirbuster.sh shortcut in /usr/bin
addBinEntry dirbuster "/usr/share/infond/bin/DirBuster-1.0-RC1" "java -jar DirBuster-1.0-RC1.jar" term

# add entry in Gnome menu for DirBuster
addmenu dirbuster "DirBuster is a multi threaded java application designed to brute force directories and files names on web/application servers. Often is the case now of what looks like a web server #in a state of default installation is actually not, and has pages and applications hidden within. DirBuster attempts to find these." dirbuster "true" "Pentest"

##################################
# truecrypt-7.0-linux-x86
##################################

#install
if [ -z "$(ls /usr/share/infond/bin | grep truecrypt)"  ];then
  wget http://www.truecrypt.org/download/truecrypt-7.0-linux-x86.tar.gz -nc -P /tmp
  log "+" "truecrypt-7.0 downloaded"
  tar xzf /tmp/truecrypt-7.0-linux-x86.tar.gz -C /usr/share/infond/bin/
  rm /tmp/truecrypt-7.0-linux-x86.tar.gz
  /usr/share/infond/bin/truecrypt-7.0-setup-x86
  log "+" "truecrypt-7.0 installed"
else
  log "I" "truecrypt-7.0 already downloaded. Not updated."
fi

# add category to gnome menu
addcategory truecrypt Accessories

##################################
# - metasploit framework 3.4.1-linux-i386
##################################

# install
if [ -z "$(ls /usr/share/infond/bin | grep framework-3.4.1)"  ];then
  wget http://www.metasploit.com/releases/framework-3.4.1-linux-i686.run -nc -P /usr/share/infond/bin/
  log "+" "metasploit framework 3.4.1 downloaded"
  bash /usr/share/infond/bin/framework-3.4.1-linux-i686.run 
  log "+" "metasploit framework 3.4.1 installed"
else
  log "I" "metasploit framework 3.4.1 already downloaded. Not updated."
fi

# download icon
downloadicon msfconsole http://www.metasploit.com/images/hax_small.jpg

# add msfconsole entry in Gnome menu
addmenu msfconsole "The Metasploit Framework is both a penetration testing system and a development platform for creating security tools and exploits." "bash -c 'echo msfconsole;msfconsole -v;msfconsole'" "true" "Pentest" 

###########################
# wipe
###########################

# apt install
aptinstall wipe

# download icon
downloadicon wipe http://i26.tinypic.com/141o2nt.jpg

# add entry in Gnome menu
addmenu wipe "securely erase files from magnetic media." "bash -c 'cd /tmp;wipe -h;bash'" "true" "Accessories"

###########################
# ascii
###########################

# apt install
aptinstall ascii

# download icon
downloadicon ascii http://ascii-table.com/img/table.gif

# add entry in Gnome menu
addmenu ascii "table ascii." "bash -c 'ascii -h;bash'" "true" "Accessories"


###########################
# aircrack-ng
###########################

# apt install
aptinstall aircrack-ng

# download icon
downloadicon aircrack http://www.hebertphp.net/wordpress/wp-content/uploads/2009/07/wifi.jpg 

# add entry in Gnome menu
addmenu aircrack "Aircrack-ng is an 802.11 WEP and WPA-PSK keys cracking program that can recover keys once enough data packets have been captured. It implements the standard FMS attack along with some optimizations like KoreK attacks, as well as the all-new PTW attack, thus making the attack much faster compared to other WEP cracking tools. In fact, Aircrack-ng is a set of tools for auditing wireless networks." "bash -c 'cd /tmp;aircrack-ng --help;bash'" "true" "Pentest"

###########################
# firefox extensions
###########################

# close firefox
[ ! -z $(pidof firefox-bin) ] && kill -9 $(pidof firefox-bin)

# download and install firefox extensions
firefoxadd firebug 1843
firefoxadd livehttpheaders 3829
firefoxadd noscript 722
firefoxadd flashblock 433
firefoxadd flashgot 220
firefoxadd foxyproxy 2464

# tamper_data-11.0.1-fx
# does not use "latest" address. Must download specific version.
if [ -z "$(ls -R /usr/lib/firefox-addons/extensions | grep tamperdata)" ]; then 
  wget https://addons.mozilla.org/fr/firefox/downloads/file/79565/tamper_data-11.0.1-fx.xpi -nc -P /usr/lib/firefox-addons/extensions
  log "+" "tamper_data ready to install."
else
 log "I" "tamper_data already installed. .xpi not downloaded."
fi

# install firefox addons
firefox -silent -offline

# EOF
